<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'HumusBase\Module'                                                                       => __DIR__ . '//Module.php',
    'HumusBase\Doctrine\ArrayToObjectMapper\Exception\InvalidArgumentException'              => __DIR__ . '//src/Doctrine/ArrayToObjectMapper/Exception/InvalidArgumentException.php',
    'HumusBase\Doctrine\ArrayToObjectMapper\Exception'                                       => __DIR__ . '//src/Doctrine/ArrayToObjectMapper/Exception.php',
    'HumusBase\Doctrine\ArrayToObjectMapper\ArrayToEntityMapper'                             => __DIR__ . '//src/Doctrine/ArrayToObjectMapper/ArrayToEntityMapper.php',
    'HumusBase\Doctrine\ArrayToObjectMapper\ArrayToObjectMapperInterface'                    => __DIR__ . '//src/Doctrine/ArrayToObjectMapper/ArrayToObjectMapperInterface.php',
    'HumusBase\Model\AbstractModel'                                                          => __DIR__ . '//src/Model/AbstractModel.php',
    'HumusBase\Zend\EventManager\StaticListenerAggregate\StaticListenerAggregateInterface'   => __DIR__ . '//src/Zend/EventManager/StaticListenerAggregate/StaticListenerAggregateInterface.php',
    'HumusBase\Zend\EventManager\StaticListenerAggregate\Exception\InvalidArgumentException' => __DIR__ . '//src/Zend/EventManager/StaticListenerAggregate/Exception/InvalidArgumentException.php',
    'HumusBase\Zend\EventManager\StaticListenerAggregate\Exception'                          => __DIR__ . '//src/Zend/EventManager/StaticListenerAggregate/Exception.php',
    'HumusBase\Zend\EventManager\StaticListenerAggregate\StaticListenerAggregate'            => __DIR__ . '//src/Zend/EventManager/StaticListenerAggregate/StaticListenerAggregate.php',
);