<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'HumusBase\Module'                                                                       => __DIR__ . '//Module.php',
    'HumusBase\Util\Exception\RuntimeException'                                              => __DIR__ . '//src/HumusBase/Util/Exception/RuntimeException.php',
    'HumusBase\Util\Exception'                                                               => __DIR__ . '//src/HumusBase/Util/Exception.php',
    'HumusBase\Util\String'                                                                  => __DIR__ . '//src/HumusBase/Util/String.php',
    'HumusBase\Doctrine\ORM\ArrayToEntityMapper'                                             => __DIR__ . '//src/HumusBase/Doctrine/ORM/ArrayToEntityMapper.php',
    'HumusBase\Doctrine\Common\ArrayToObjectMapper'                                          => __DIR__ . '//src/HumusBase/Doctrine/Common/ArrayToObjectMapper.php',
    'HumusBase\Model\AbstractModel'                                                          => __DIR__ . '//src/HumusBase/Model/AbstractModel.php',
    'HumusBase\Zend\EventManager\StaticListenerAggregate\StaticListenerAggregateInterface'   => __DIR__ . '//src/HumusBase/Zend/EventManager/StaticListenerAggregate/StaticListenerAggregateInterface.php',
    'HumusBase\Zend\EventManager\StaticListenerAggregate\Exception\InvalidArgumentException' => __DIR__ . '//src/HumusBase/Zend/EventManager/StaticListenerAggregate/Exception/InvalidArgumentException.php',
    'HumusBase\Zend\EventManager\StaticListenerAggregate\Exception'                          => __DIR__ . '//src/HumusBase/Zend/EventManager/StaticListenerAggregate/Exception.php',
    'HumusBase\Zend\EventManager\StaticListenerAggregate\StaticListenerAggregate'            => __DIR__ . '//src/HumusBase/Zend/EventManager/StaticListenerAggregate/StaticListenerAggregate.php',
);